-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 22:47:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------
CREATE DATABASE db_pizzaria_legal;
-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------
CREATE SCHEMA  `db_pizzaria_legal` DEFAULT CHARACTER SET utf8 ;
USE `db_pizzaria_legal` ;

-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizza` (
  `idtb_pizza` INT NOT NULL AUTO_INCREMENT,
  `sabor` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(4,2) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `tamanho` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_pizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_categoria` (
  `id` INT UNSIGNED NOT NULL,
  `opcoes` VARCHAR(100) NOT NULL,
  `tamanho` VARCHAR(45) NOT NULL,
  `fk_tb_pizza_tipo` INT NOT NULL,
  PRIMARY KEY (`id`, `fk_tb_pizza_tipo`),
  INDEX `fk_tb_categoria_tb_pizza_idx` (`fk_tb_pizza_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_tb_categoria_tb_pizza`
    FOREIGN KEY (`fk_tb_pizza_tipo`)
    REFERENCES `db_pizzaria_legal`.`tb_pizza` (`idtb_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
